### ISSUE TITLE
移动端 - 整体布局

### ISSUE THREAD

**Issue by wamxb** [wamxb/blog#10]
flex布局

``` css
html, body, .g-doc { overflow: hidden; height: 100%; }
body, .g-doc { display: -webkit-box; display: -ms-flexbox; display: -webkit-flex; display: flex; -webkit-flex-direction: column; -ms-flex-direction: column; flex-direction: column; background-color: #fff; -webkit-box-orient: vertical; }
.g-bd { overflow-y: auto; -webkit-overflow-scrolling: touch; -webkit-box-flex: 1; -ms-flex: 1; -webkit-flex: 1; flex: 1; }
.g-hd, .g-ft { height: 44px; background-color: #fff; text-align: center; line-height: 44px; position: relative; z-index: 990; }
.g-hd { border-bottom: 1px solid #f00; }
.g-ft { border-top: 1px solid #f00; }
```

绝对定位布局

``` css
* { -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; }
html, body, .g-doc { height: 100%; }
body, .g-doc { position: relative; }
/* ==================================================
layout
================================================== */
.g-hd,
.g-bd,
.g-ft { position: absolute; left: 0; right: 0; }
.g-bd { top: 44px; bottom: 44px; overflow-y: auto; -webkit-overflow-scrolling: touch; }
.g-hd,
.g-ft { height: 44px; background-color: #fff; text-align: center; z-index: 900; line-height: 44px; }
.g-hd { top: 0; border-bottom: 1px solid #f00; }
.g-ft { bottom: 0; border-top: 1px solid #f00; }
```
