### ISSUE TITLE
input

### ISSUE THREAD

**Issue by wamxb** [wamxb/blog#17]
### 如何写好输入框
1.  在书写输入框的时候，如果要增加光标高度，那么最可行的做法是增加文字的大小；
2.  输入框的剩余空白使用内边距填充；
3.  不要为输入框设置行高，因为浏览器默认会设置行高就会使占位符和输入光标、文字都居中`line-height: normal`；
4.  不要为输入框设置高度，因为已经使用了内边距撑开了，并且现在大多数css库都直接使用边框盒模型；
### input的高度计算

先说`input`，这里说的`input`垂直居中，是指`input`内部文字的居中。
`input`框在各种浏览器效果一样的解决法案：
为`input`框定义这样的`css`

``` css
.inputText{
font-size:12px;
height:14px;
padding:5px;
line-height:15px;
}
```

则`input`的高度最后为`26px`；
下面解释
`height = fontSize + 2px`
`lineHeight = height + 1px`
`input_Height = height + paddingTop + paddingBottom + 2`

[css实现input、checkbox垂直居中](http://www.ghugo.com/css-to-achieve-input-checkbox-vertical-center/)
