### ISSUE TITLE
scrollbar

### ISSUE THREAD

**Issue by wamxb** [wamxb/blog#18]
``` css
::-webkit-scrollbar {
    width: 5px;
    height: 5px
}

::-webkit-scrollbar-track-piece {
    background-color: rgba(0,0,0,.2);
    -webkit-border-radius: 6px
}

::-webkit-scrollbar-thumb:vertical {
    height: 5px;
    background-color: rgba(125,125,125,.7);
    -webkit-border-radius: 6px
}

::-webkit-scrollbar-thumb:horizontal {
    width: 5px;
    background-color: rgba(125,125,125,.7);
    -webkit-border-radius: 6px
}
```

[SCRAT - webapp模块化开发体系](http://scrat-team.github.io)
