### ISSUE TITLE
opacity

### ISSUE THREAD

**Issue by wamxb** [wamxb/blog#19]
背景透明 文字不透明css写法：

``` css
.submenu{background:rgba(0,0,0,.5);background-color:#000000\9;filter:alpha(opacity=50); }
.submenu a{ color:#fff;}
```
