### ISSUE TITLE
center-box

### ISSUE THREAD

**Issue by wamxb** [wamxb/blog#21]
``` css
/* 去除 inline-block 的空隙 */
.center-box {
    height: 100%;
    *word-spacing: -1px; /* IE6、7 */
    font-size: 0; /* 继承父级高度 */
    }
/* 修复 Safari 5- inline-block 的空隙 */
@media (-webkit-min-device-pixel-ratio: 0) {
    .center-box {
        letter-spacing: -5px;
        }
    }
/* 使用空标签生成一个高度100%的参照元素 */
.center-box .center-hack {
    display: inline-block;
    *display: inline;
    width: 0;
    height: 100%;
    vertical-align: middle;
    font-size: 0;
    *zoom: 1;
    }
.center-box .center-body {
    display: inline-block;
    *display: inline;
    margin: 0 !important;
    padding: 0 !important;
    width: 100%;
    vertical-align: middle;
    white-space: normal;
    word-spacing: normal; /* 保证文字垂直居中 */
    word-wrap: break-word; /* 防止设置边距导致居中失效 */
    letter-spacing: normal;
    font-size: 12px; /* 保证连续字符也能居中 */
    *zoom: 1; /* 保证连续字符换行 */
    }
.center-box .center-img {
    display: inline-block;
    *display: inline;
    margin: 0 !important;
    padding: 0 !important;
    width: 100%;
    vertical-align: middle; /* 图片默认水平居中 */
    text-align: center;
    *zoom: 1; /* 防止设置边距导致居中失效 */
    }
.center-box img {
    vertical-align: middle; /* 去除现代浏览器 img 底部空隙 */
    }
```
