### ISSUE TITLE
HTML布局之左右结构

### ISSUE THREAD

**Issue by wamxb** [wamxb/blog#33]
### HTML布局之垂直居中
1. 设置 display: table-cell

``` html
<div class="box">
    <div class="con">con</div>
</div>
```

``` css
.box {
    width: 100px;
    height: 100px;
    display: table-cell;
    vertical-align: middle;
    background-color: #03c6a8;
}
.con {
    width: 50px;
    height: 50px;
    margin: 0 auto;
    background-color: #0a727d;
}
```
### HTML布局之左右结构

``` html
<ul>
    <li class="item">
        <label class="item-title" for="">邮箱：</label>
        <div class="item-con">
            <input class="input" placeholder="常用邮箱" type="text" />
            <p class="tips-text">6~18个字符，可使用字母、数字、下划线，需以字母开头</p>
        </div>
    </li>
    <li class="item">
        <label class="item-title" for="">密码：</label>
        <div class="item-con">
            <input class="input" type="text" />
            <p class="tips-text">6~16个字符，区分大小写</p>
        </div>
    </li>
    <li class="item">
        <label class="item-title" for="">确认密码：</label>
        <div class="item-con">
            <input class="input" type="text" />
            <p class="tips-text">请再次填写密码</p>
        </div>
    </li>
</ul>
```

1.用display: table-cell 模拟 table，IE67不支持

``` css
.item {
    display: table;
}
.item-title {
    width: 100px;
    text-align: right;
    display: table-cell;
}
.item-con {
    display: table-cell;
    padding-left: 5px;
}
```

2.左侧标题 float:left，右侧控件 margin-left

``` css
 .item1 {
        overflow: hidden;
    }
    .item-title1 {
        width: 100px;
        text-align: right;
        float: left;
    }
    .item-con1 {
        margin-left: 100px;
        padding-left: 5px;
    }
```

3.【√】左侧标题float:left，右侧控件overflow: hidden;

``` css
.item2 {
        overflow: hidden;
    }
    .item-title2 {
        width: 100px;
        text-align: right;
        float: left;
    }
    .item-con2 {
        padding-left: 5px;
        overflow: hidden;
        zoom: 1; /* for ie67*/
    }
```

4.定位

``` css
 .item3 {
        position: relative;
    }
    .item-title3 {
        width: 100px;
        text-align: right;
        position: absolute;
        left: 0;
        top: 0;
    }
    .item-con3 {
        padding-left: 5px;
        margin-left: 100px;
    }
```

http://blog.jayself.com/2014/01/19/html_layout_lr/
