### ISSUE TITLE
重构のem

### ISSUE THREAD

**Issue by wamxb** [wamxb/blog#39]
`em`是一个相对的大小，这里的相对所指的是相对于元素的父元素`font-size`
`em`实际上是一个垂直测量。一个`em`等于任何字体中的字母所需要的垂直空间，而和它所占据的水平空间没有任何的关系

``` css
html {font-size: 100%;}
body {font-size: 1em; }
```

1、字体计算公式依旧  `1 ÷ 父元素的font-size × 需要转换的像素值 = em值`
2、其它属性的计算公式需要换成 `1 ÷ 元素的font-size × 需要转换的像素值 = em值`
