### ISSUE TITLE
重构の透明度

### ISSUE THREAD

**Issue by wamxb** [wamxb/blog#43]
``` css
.f-opacity5 {
-ms-filter: "progid:DXImageTransform.Microsoft.gradient(GradientType=1,startColorstr=#7f000000,endColorstr=#7f000000)"; /*Filter for IE8 */   
filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#7f000000, endColorstr=#7f000000); /*Filter for older IEs */
background-color:#000;
 background-color: rgba(0, 0, 0, .5);
 }
```

PS：#7f000000 其中7f是透明度0.5转换成16进制的数值，000000是黑色的16进制数值 

![rgba和IE下filter数值转换](http://img.caibaojian.com/uploads/2015/06/rgba.png)
