### ISSUE TITLE
css3序列帧动画写法

### ISSUE THREAD

**Issue by wamxb** [wamxb/blog#45]
``` css
/* 两倍写法 bg(406*100) */
.flow { height: 50px; width: 50px; background: url("flow_sprite.png") no-repeat 0 0; -webkit-background-size: auto 50px; -webkit-animation: flow .5s steps(3, start) infinite; }
        @-webkit-keyframes flow {
            100% { background-position: -153px 0; }
            }
```

[demo](http://jsbin.com/zovapa/23/edit?html,css,output)
