### ISSUE TITLE
重构の清除浮动&闭合浮动&BFC

### ISSUE THREAD

**Issue by wamxb** [wamxb/blog#5]
### 清除浮动

``` css
/**
 * 写法1：
 * For modern browsers
 * :before 用来处理margin边距叠加
 */
.f-cb:before,
.f-cb:after {content:"";display:table;}
.f-cb:after {clear:both;}
/**
 * For IE 6/7 (trigger hasLayout)
 */
.f-cb {*zoom:1;}

/**
 * 写法2：NEC
 */
.f-cb:after {display:block;clear:both;visibility:hidden;height:0;overflow:hidden;content:".";}
.f-cb {zoom:1;}
```

_firefox直到7.0 content:”" 仍然会产生额外的空隙；_
_参考网址_
1.http://cssmojo.com/latest_new_clearfix_so_far/
2.http://nec.netease.com/framework/css-function.html
### 闭合浮动
1. 添加额外标签
   缺点：会添加多少无意义的空标签，有违结构与表现的分离（×）
2. 使用 br标签和其自身的 html属性
   缺点：同样有违结构与表现的分离，不推荐使用（×）
3. 父元素设置 overflow：hidden
   缺点：内容增多时候容易造成不会自动换行导致内容被隐藏掉，无法显示需要溢出的元素（×）
4. 父元素设置display:table
   缺点：盒模型属性已经改变，由此造成的一系列问题，得不偿失（×）
   https://jsfiddle.net/zplus/gp9dpr3t/
### Block Formatting Context

Block Formatting Context（块格式化上下文）,决定了元素如何对其内容进行定位，以及与其他元素的关系和相互作用
IE8之前的版本中，没有提到Block Formatting Context的概念，而是用私有属性hasLayout来达到相似的目。

可生成 Block Formatting Context 的 CSS 特性：

> - float: ( 除 none 外的任何值 )
> - overflow: ( 除 visible 外的任何值 )
> - display: ( table-cell，table-caption 或 inline-block )
> - position: ( 除 relative 和 static 外任意值 )

可触发 hasLayout 的 CSS 特性：

> - display: inline-block
> - height: (除 auto 外任何值) （例如很多人闭合浮动会用到 height: 1%） 
> - width: (除 auto 外任何值)
> - float: (left 或 right)
> - position: absolute
> - writing-mode: tb-rl
> - zoom: (除 normal 外任意值)

目前最好的解决方案就是使元素即生成 Block Formatting Context，又触发 hasLayout。IE下通过设置“zoom:1”，便可触发 hasLayout。
### BFC的特性
1. 块级格式化上下文会阻止外边距叠加
2. 块级格式化上下文不会重叠浮动元素
3. 块级格式化上下文通常可以包含浮动

_参考地址_
1.http://www.feelcss.com/block-formatting-context-can-help-what-we-do.html
2.http://www.iyunlu.com/view/css-xhtml/55.html
