### ISSUE TITLE
css3のprogress

### ISSUE THREAD

**Issue by wamxb** [wamxb/blog#52]
用很挫的定位方式写了progressbar，望高手指点

``` css
        * { margin: 0; padding: 0; }
        ul { list-style: none; }
        .progress { position: relative; overflow: hidden; margin: 100px; width: 200px; height: 6px;  }
        .progress ul { position: absolute; left: 0; overflow: hidden; width: 100%; height: 100%; color: #ddd; }
        .progress ul.active { color: orange; }
        .progress ul:before { position: absolute; top: 50%; left: 0; width: 100%; height: 2px; background: currentColor; content: ""; -webkit-transform: translate(0, -50%); }
        .progress li { position: absolute; top: 0; width: 6px; height: 6px; -webkit-border-radius: 999px; background: currentColor; }
        .progress li:nth-of-type(1) { left: 0; }
        .progress li:nth-of-type(2) { left: 40px; }
        .progress li:nth-of-type(3) { left: 80px; }
        .progress li:nth-of-type(4) { left: 120px; }
        .progress li:nth-of-type(5) { left: 160px; }
        .progress li:nth-of-type(6) { left: 194px; }
```

```
<div class="progress">
    <ul class="back">
        <li></li><li></li><li></li><li></li><li></li><li></li>
    </ul>
    <ul class="active" style="width: 31%">
        <li></li><li></li><li></li><li></li><li></li><li></li>
    </ul>
</div>
```

[demo](http://jsbin.com/tamope/4/edit?html,css,output)

**Comment by zplus** [comment]
觉得太多标签再写个蛋疼的demo
```html
<div class="progress">
    <div class="bg"></div>
    <div class="active" style="width: 50%"></div>
</div>
```

```css
* { margin: 0; padding: 0; }
ul { list-style: none; }
body { background: #fff; }
.progress { position: relative; overflow: hidden; margin: 100px; width: 200px; height: 6px; background: #fff; }
.progress > div { position: absolute; top: 0; left: 0; overflow: hidden; height: 100%; }
.progress > div.bg { width: 100%; background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #fff), color-stop(33%, #fff), color-stop(33%,
#eee), color-stop(33%, #eee), color-stop(66%, #eee), color-stop(66%, #fff), color-stop(100%, #fff)); color: #eee; }
.progress > div.active { background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #fff), color-stop(33%, #fff), color-stop(33%,
orange), color-stop(33%, orange), color-stop(66%, orange), color-stop(66%, #fff), color-stop(100%, #fff)); color: orange; }
.progress > div:before { position: absolute; top: 0; left: 0; width: 6px; height: 6px; border-radius: 9999px; background: currentColor; -webkit-box-shadow: 40px 0 0 currentColor, 80px 0 0 currentColor, 120px 0 0 currentColor, 160px 0 0 currentColor, 194px 0 0 currentColor; content: ""; }
.progress > div.bg:before { color: #eee; }
.progress > div.active:before { color: orange; }
```

[demo](http://jsbin.com/loleto/5/edit?html,css,output)
