### ISSUE TITLE
重构の1定1适等高布局

### ISSUE THREAD

**Issue by wamxb** [wamxb/blog#53]
### [demo1](http://jsbin.com/dazebo/28/edit?html,css,output)

``` html
<div id="container">
    <div id="wrapper">
        <div id="sidebar"></div>
        <div id="main"></div>
    </div>
</div> 
```

``` css
#container { background: blue; }
#wrapper { border-left: 200px solid red; /*==此值等于左边栏的宽度值==*/ 
display: inline-block; position: relative; vertical-align: bottom; }
#maing, #sidebar { min-height: 200px; height: auto !important; height: 200px; }
#sidebar { margin-left: -200px; /*==此值等于左边栏的宽度值==*/
position: relative; float: left; width: 200px; }
#main { float: left; }
```
### [demo2](http://jsbin.com/jupixu/3/edit?html,css,output)

``` html
 <div id="container">
        <div id="left" class="aside"></div>
        <div id="content" class="section"></div>
</div>
```

``` css
* { margin: 0; padding: 0; }
#container { overflow: hidden; }
#left { float: left; margin-bottom: -99999px; padding-bottom: 99999px; width: 200px; background: #ccc; }
#content { margin-left: 200px; /*==此值等于左边栏的宽度值==*/
margin-bottom: -99999px;  padding-bottom: 99999px; background: #eee; }
#left, #content { min-height: 200px; height: auto !important; height: 200px; }
```
### [demo3](http://jsbin.com/nuhetu/1/edit?html,css,output)

``` html
 <div id="container">
        <div id="content"></div>
        <div id="sidebar"></div>
    </div>
```

``` css
     *{margin: 0;padding: 0;}
         #container{
             background-color:#0ff;
             overflow:hidden;
             padding-left:220px; /* 宽度大小等与边栏宽度大小*/
         }
         * html #container{
             height:1%; /* So IE plays nice */
         }
         #content{
             background-color:#0ff;
             width:100%;
             border-left:220px solid red;
             margin-left:-220px;
             float:right;
         }
         #sidebar{
             background-color:red;
             width:220px;
             float:right;
             margin-left:-220px;
         }
         #content,
         #sidebar {
             min-height: 200px;
             height: auto !important;
             height: 200px;
         }
```

参考网址：http://www.w3cplus.com/css/two-cloumn-width-one-fixed-width-one-fluid-width
