### ISSUE TITLE
前端开发中的一些黑魔法[note]

### ISSUE THREAD

**Issue by wamxb** [wamxb/blog#65]
# 表格行和列高亮显示

``` scss
table {
  overflow: hidden;
  td,
  th {
    position: relative;
  }
  tr:hover {
    background-color: #ffa;
  }
  th:hover::after,
  td:hover::after {
    content: "";
    position: absolute;
    width: 100%;
    height: px2rem(10000);
    left: 0;
    top: px2rem(-5000);
    background-color: #ffa;
    z-index: -1;
  }
}
```

from: [http://www.w3cplus.com/css/dirty-tricks-dark-corners-front-end-pt1.html](http://www.w3cplus.com/css/dirty-tricks-dark-corners-front-end-pt1.html)
